// ==========================================
// 1. DATASET: 103 QROC Pédiatrie Questions
// ==========================================
const questions = [
  { id: 1, lang: "fr", page: "78", q: "1. Critère du diagnostique du syndrome néphrotique.", a: "R: critère du diagnostique du syndrome néphronique\n- nephrotic range proteinurie\n- hypoalbuminémie\n- edema\n- hyperlipidémie" },
  { id: 2, lang: "fr", page: "78", q: "2. Quelles sont les complications cardiovasculaires de la glomérulonéphrite post-infectieuse?", a: "R: Les complications cardiovasculaires de la glomérulonéphrite postinfectieuse sont:\n- volume overload\n- hypertension\n- hyperkalemia\n- hypocalcemia\n- seizure\n- elevated serum creatinine and urea." },
  { id: 3, lang: "en", page: "78", q: "3. Diagnosis of filariasis (15mn)", a: "R: - Parasite adulte: Biopsie ganglionnaire\nMicrofilaire: Dans le sang prélèvement pendant la nuit vers 23h ou 1h la prise de 1cp (100mg) de Notétézine\nDans le liquide chyleux: épanchement vaginal, pleural, varice lymphatique, chylurie..." },
  { id: 4, lang: "fr", page: "78", q: "4. Quels sont les facteurs intervenants dans le développement somatique de l'enfant(5mn)", a: "R: Les factures intervenants dans le développement somarique de l'enfant:\n+ Croissace\nTaille (staturale)\nPonds\nSurface corporelle\n+ Maturation\nAge des dent\nAge osseux\nMaturation sexually\nCritères neurologiques\nRapports anthropométriques" },
  { id: 5, lang: "en", page: "78", q: "5. Descripes the treatment of idiopathic thrombocytopenia pupura.", a: "R: Oral Prednisolone: 2mg/kg/day for 14days then taper and discontinue at 21 days (Max: 60mg/day)\n- IV Methylprednisolone: 30mg/kg/day for 3days\n- IVIG: 0.8g/kg/dose over 3 hours for 1day or 250mg/kg for 2 days\n- IV anti-D immunoglobulin: 50ug/kg single dose over 5mn in Rhesus positive patients" },
  { id: 6, lang: "kh", page: "78", q: "6. រៀបរចាប់ពី principe ដែលធ្វើអោយépiglottite.", a: "R:\n- Epiglotte inflammé et souvent abcèdée devient enorme boucher le trou de glotte\n- Presque toujour due a Hemophilus influenza\n- Syndrome de dyspné larygnée, des signes généraux importants avec fièvre, l'enfant est assis ou 4 pattes, la dysphagiee" },
  { id: 7, lang: "fr", page: "78", q: "7. Citez les signes cliniques et paracliniques de la fièvre dengue hémorragique.", a: "+ signes cliniques\nFebrile phase:\n• Clinical signs & symptoms are similar to DF.\n• Manifestations of bleeding is evidenced than DF:\nPositive tourniquet test\n- Petechiae\n- Ecchymosis, Epistaxis\nGum and Gl bleeding\n- Afebrile: Critical phase \"24h-48h\"\n• Fever starts to drop, usually on day 4 or 5 of disease, but:\nGeneral condition become deterioration\n- Somnolent\nAsthenia\n- Severe vomiting\n- Severe abdominal pain\nNo urine output 4 - 6h\n+ Signes paraclinique :\n- Thrombocytopenia (platelet <100 000/mm3\n- Signs of plasma leakage:\n• Hemoconcentration → Hct ↑(>20% of Hct baseline).\n• Other plasma leakage signs:\n. Pleural effusion\n. Ascites\n. Hypoalbuminemia" },
  { id: 8, lang: "fr", page: "78", q: "8. Qeuls sont les moyens de diagnostic d'une méningite chez l'enfant?", a: "R: Les moyens de diagnostic d'une méningite chez l'enfant:\n- Syndrome infectieux: Fièvre à début souvent brutal\n- Syndrome méningé: céphalée, vomissement\n- Examen:\n+ Raideur de ka nuque\n+ signe de kernig\n+ signe de brudzinski" },
  { id: 9, lang: "fr", page: "78", q: "9. Élements de gravité du Paludisme?", a: "R: Les éléments de gravité :\n- coma, convulsion - ictère\n- hypogycémie\n- insuffisance rénale - parasitémie>5%\n- anémie grave\n- hémoglobinurie - OAP\n- Déshydratation - Thrombopénie" },
  { id: 10, lang: "fr", page: "78", q: "10. Citez vous les trois grands mécanismes de l'anémie du nourrisson.", a: "R: Trois grands mécanismes de l'anémie :\n- le défaut de production de GR qui est le plus souvent lié à une étiologie carentielle;\n- la destruction augmentée de GR dans le cadre d'une hémolyse;\n- la perte de GR lié à une hémorragie" },
  { id: 11, lang: "en", page: "78", q: "11. Clinical signs of pleural effusion ?", a: "- Fever\nDry cough\n- Dyspnea (more or less marked depending on the abundance of the effusion)\nChest pain\n- Immobility of a hemithorax\n- MV or O\nMatity" },
  { id: 12, lang: "kh", page: "78", q: "12. Diagnostic et examen de laboratoire នៃជំងឺក្អកមាន់?", a: "Diagnosis:\n- Période de début: toux, émétisante, nocturne, Fièvre modérée (37,5°c-38°c)\n- Période des quintes (7 à 10 jours), cyanose.\nPhase de déclin des quintes.\nExamen de laboratroire :\n+ Test Elisa anti corps anti - Bordetella pertussis\n+ Hyperlymphocytose (10 000 à 30 000 Leucocyles dont 60 à 90% de lymphocytes).\n+ Radiographie de thorax: parfois atélectasie." },
  { id: 13, lang: "fr", page: "78", q: "13. Citez les signes cliniques rhino-pharyngite de l'enfant au-dessous de 2ans ?", a: "- L'encombrement ORL, Fievre, Dsyphagie (anorexie brutale pour les alimentations solides)\n- L'inflammation nasale: (gene respiratoire, le jettage nette)\nVm, selles les glaires ingeres ou une diarrhee authentique\n- L'evolution est favorable" },
  { id: 14, lang: "en", page: "78", q: "14. Complication de la fièvre thyphoide?", a: "Intestinal hemorrhage\nIntestinal perforation\nToxic hepatitis\nToxic myocarditis\nBronchitis, bronchopneumonia" },
  { id: 15, lang: "fr", page: "78", q: "15. Traitement de l'ictère à bilirubine libre ?", a: "Apport nutritionnel precoce\nPhototherapie\n- Albumine\nExsanguino-transfusion\n- Prevention de l'hemorragie" },
  { id: 16, lang: "en", page: "78", q: "16. What are the risks factors of asthma ?", a: "Host factors\nGenetic\nGenes pre-disposing to atopy\nGenes pre-disposing to airway hyper-responsiveness\nObesity\nSex\nEnvironmental factors\nAllergens\nIndoor: Domestic mites, furred animals (dogs, cats, mice), cockroach allergens, fungi, moulds, yeasts\nOutdoor: Pollens, fungi, moulds, yeasts\n• Infections (predominantly viral)\nOccupational sensitizers\nTobacco smoke\nPassive smoking\nActive smoking\nOutdoor/Indoor Air Pollution\nDiet" },
  { id: 17, lang: "en", page: "78", q: "17. Diagnosis of Trichinosis (trichinella spiralis)?", a: "- serology\n- muscle biopsy for Trichinella\nmore compatible clinical symptoms (eosinophilia, fever, myalgia, facial or periorbital edema).\n- Antibodies to Trichinella are detectable approximately 3 wk after infection" },
  { id: 18, lang: "kh", page: "78", q: "18. ចូរនិយាយអំពី définition របស់ Nephrotic syndrome ?", a: "- Nephrotic range proteinuria:\n• > 50 mg or 0.05g/kg/24h or\n• Dipstick 3-4+ or\n• Urine protein/creatinine ratio >2\nHypoalbuminemia <30g/L\nEdema\nHyperlipidemia" },
  { id: 19, lang: "en", page: "78", q: "19. Clinical manifestation of Guillian Barre syndrome ?", a: "- begin with muscle paralysis symmetrical rapidly progress in an ascending fashion over periode of hour to day\n- affect of nerve cranial (drooling, difficulty swallowing)\n- 30% affect autonomic nerves\n- loss of pain, temperature, bladder dysfunction, orthopedic hypotension" },
  { id: 20, lang: "en", page: "78", q: "20. Clinical manifestation of Encephalitis?", a: "fever, delirium, or confusion and abnormal behavior present. progressing to unconsciousness, seizure cranial nerve ( palsies, paresis and paralysis), involuntary movement, reflexes. Signs of marked ICP may be" },
  { id: 21, lang: "kh", page: "78", q: "21. តើជំងឺ hemophilia កើតឡើងដោយសារមូលហេតុអ្វី?", a: "caused by a mutation or change, in one of the genes, that provides instructions for making the clotting factor proteins needed to form a blood clot.it cause of low levels of either factor VIII (8) or factor IX (9).\n- Complete blood count (CBC) PTL count normal. Hemostasis tests: bleeding Time (normal), PT (normal), aPTT (prolonged).\n- Factor assay: test shows the type and severity of hemophilia\nCarriers and Prenatal diagnosis: DNA test is the most accurate test for carrier, Amniocentesis." },
  { id: 22, lang: "kh", page: "78", q: "22. តើស្តេសអ្វីខ្លះដើម្បីធ្វើរោគវិនិច្ឆ័យដើម្បីរកជំងឺ Thalassemia ?", a: "- Take blood to check (anemia and abnormal hemoglobin)\n- Microscope: red blood cell have a body shaped.\nHemoglobin electrophoresis\n- severe splenomegaly might hemoglobin H disease" },
  { id: 23, lang: "fr", page: "78", q: "23. Quelle est la définition de la convulsion fébrile ?", a: "La Convulsion fébrile: un événement survenant habituellement chez un nourrisson ou un enfant entre 6 mois et 5 ans, associé à de la fiévre, sans signe d'infection intracrânienne ou autre cause définie, à l'exclusion des convulsions avec fièvre survevant chez un enfant ayant déjà présenté des convulsions sans fiévre." },
  { id: 24, lang: "kh", page: "78", q: "24. Clinical signs of JE មានអ្វីខ្លះ? ចូររៀបរាប់ ។", a: "A prodromal stage\n- Lasts for 1-6 days\n- Fever, Rigor\n- Headache\nGastrointestinal problems\n- Lethargy\n- Malaise\nAcute encephalitis stage\n- Convulsions\n- Altered sensorium, unconsciousness, coma\n- Tremors in fingers, tongue, eyelids and eyes\n- Abnormal movements of limbs\nMask like face\n- Stiff neck\n- Muscular rigidity\n- Speech impairment\nLate stage & Sequelae\nCharacterized by the persistence of signs of CNS injury such as\nMental impairment\nEpilepsy, abnormal movements, behavior abnormalities\n- Paresis motor neuron type" },
  { id: 25, lang: "kh", page: "78", q: "25. ចូររៀបរាប់អំពី les facteurs de risques de prématuré", a: "កត្តាម្តាយ\n- ស្ថានភាពម្តាយ : ធាត់ខ្លាំង ប្រវត្តិមានកូនមិនគ្រប់ខែ,អាយុម្តាយ(<18 ឆ្នាំ ឫ >35ឆ្នាំ), ផឹកស្រា ឫ ជក់បារី\nកត្តាសុខភាពម្តាយ : មានជំងឺឆ្លង, ជំងឺរ៉ាំរ៉ៃ, ជំងឺសួត\nកត្តាសង្គមសេដ្ឋកិច្ច : ការធ្វើដំណើរយូរ, មិនបានថែទាំផ្ទៃពោះ, មានរបបអាហារមិនគ្រប់គ្រាន់\nកត្តាពេលសម្រាល : មានព្រាយក្រឡាភ្លើង,មានផ្ទៃពោះច្រើនដង, មានបញ្ហារោគស្ត្រី, សុកពាំងមាត់ស្បូន\nកត្តាទារក\nកត្តាពេលសម្រាល : មានបញ្ហាក្រូម៉ូ,ទារកថប់ដង្ហើម ឫ ខ្សោយ, ទារកមានការលូតលាស់មិនល្អ, ស្ថានភាពក្រុមឈាមមិនល្អ\n• កត្តាសុខភាពទារក : មានជំងឺឆ្លងមកពីម្តាយ, រងការប៉ះទង្គិចតិច ឫ ខ្លាំង ញឹកញាប់, រងការប៉ះពាល់ពេលម្តាយប្រើថ្នាំមួយចំនួន\n• កត្តាវិភាគនៅមន្ទីរពិសោធន៍ : bilirubine, acidose, hypoglycémie" },
  { id: 26, lang: "fr", page: "78", q: "26. Diagnostic de pleurésie purulente ?", a: "Signes clinique + Radiographie / Échographie/ TDM/IRM => Pleurésie\nPleurésie: Purulent\nChimique: liquide riche en protéine (exsudative); pH < 7.2\nCytologie: leucocyte (GB>10000/mn et PN (>50%)\nBactériologie: + Examen direct et culture dans le milieu aérobie et anaérobie\n+ Chercher pour le TB\nNFS: Présent hyperleucocytose et prédominance de PN" },
  { id: 27, lang: "fr", page: "78", q: "27. Citez les paramètres du score d'Apgar ?", a: "Normale: 7-10\nAsphyxie Modérée : 4-6\nAsphyxie sévère: 0-3" },
  { id: 28, lang: "fr", page: "78", q: "28. Citez les paramètres du score de Silverman ?", a: "Silverman <4 => IR Légère + O2\nSilverman 4-6 => IR moyenne + CPAP\nSilverman > 6 => IR grave + Intubation, ventilation mécanique" },
  { id: 29, lang: "fr", page: "78", q: "29. Classer la méningite, l'angine streptococcique, la listeria monocytogènes, la méningite et Mycobactérium tuberculosis.", a: "[Voir le cours correspondant pour la classification selon le germe et la présentation clinique]" },
  { id: 30, lang: "fr", page: "78", q: "30. Certaines méningites sont souvent associées à des lésions crâniennes. Lesquelles? Quelle sont les paires crâniennes les plus atteintes ?", a: "[Les méningites basilaires/tuberculoses/pneumococciques. Pares crâniennes les plus atteintes: III, VI, VII, VIII]" },
  { id: 31, lang: "fr", page: "78", q: "31. Devant une méningite lymphocytaire associée à une élévation des transaminases et de la bilirubine, une thrombopénie, une hématurie et une insuffisance rénale, quel diagnostic doit être évoqué ?", a: "[Leptospirose]" },
  { id: 32, lang: "fr", page: "78", q: "32. Dans quelles circonstance une antibiothérapie parentérale anti-méningococcique doit être débutée d'emblée au domicile du patient ?", a: "[En présence d'un purpura fulminans]" },
  { id: 33, lang: "fr", page: "78", q: "33. En présence d'une méningite purulent, quelle antibiothérapie intra veineuse doit être débuté sans délai si l'examen direct du LCR retrouve des coccies gram négatif ?", a: "[Cefotaxime ou Ceftriaxone IV]" },
  { id: 34, lang: "kh", page: "78", q: "34. មូលហេតុដែលនាំអោយកុមារកើតជំងឺ MPE ?", a: "Carence en protéins et énergie\nCarence en particulier en vitamines et en oligo-éléments" },
  { id: 35, lang: "kh", page: "78", q: "35. សញ្ញាគ្លីនិកខុសគ្នារវាង Marasme និង kwashiorkor ?", a: "+ Marasmus\nHair may be normal\nOedema is absent\nVery underweight\nThin and bony face\nWrinkle skin\nVoracious appetite\nFatty liver uncommon\nSevere muscle wasting\n\n+ Kwashiorkor\nhair changes\nOedema is present\nUsually underweight\nMoon face\nScaly skin/ dermatosis\nPoor appetite\nFatty liver common\nMuscle wasting mild or absent" },
  { id: 36, lang: "kh", page: "78", q: "36. វិធីការពារ Marasme និង kwashiorkor ?", a: "+ Marasmus\nfamily planning\nImmunization program\nEncourage breastfeeding\nMaternity and child health clinic\n\n+ Kwashiorkor\nEducate mother\nAdvice to farmers\nProvide food supplements in hospital" },
  { id: 37, lang: "kh", page: "78", q: "37. ចូររៀបរាប់អំពី មូលហេតុ (Étiologie) នៃជំងឺ Staphylococcie pleuro-pulmonaire ?", a: "Étiologie នៃជំងឺ Staphylococcie pleuro-pulmonaire :\n- Germe: staphylocoque doré pathogène, coagulase positive, producteur d'exotoxine.\n- Terrain :\nAvant 6 mois\nPas de prédominance de sexe\nLes enfants hypotrophique, anciens prématuré\nLes enfants atteints de mucoviscidose, malformations pulmonaire\n- Très fréquent :\nDiabète\nSujet prématuré\nToxicomane\nSurinfection bactérienne\nPost bronchite aiguë virale\nPorteur d'une bronchopneumopathie chronique obstructive\n- មូលហេតុចូល :\nCutanée\nGastro-intestinale\nORL\nDissémination à partir d'une localisation viscérale" },
  { id: 38, lang: "kh", page: "78", q: "38. សញ្ញាគ្លីនិក និង រោគសញ្ញាបានមកពីការពិនិត្យ (symptômes et signe physiques) នៃជំងឺ Staphylococcie pleuro-pulmonaire ?", a: "Signes respiratoires: polypnée, toux sèche, tirage, cyanose\nSignes abdominaux: météorisme abdominale អាច occlusion\nSignes généraux: température 39° à 40°, asthénie, enfant abattu, pâle et grisâtre\nSignes physiques :\nUne diminution modérée du murmure vésiculaire\nUne matité\nUne défaillance cardiaque est possible" },
  { id: 39, lang: "fr", page: "78", q: "39. Les causes de laryngite ?", a: "Hémophilus influenzae\nVirale et bactérienne\nFausses membranes de la diphtérie laryngée (rare)\nCorp étranger (laryngite glottique ou croup)" },
  { id: 40, lang: "fr", page: "78", q: "40. Les symptômes de laryngite ?", a: "Dyspnée laryngée\nBradypnées inspiratoires avec tirage, sus sternale signant l'origine haute et cornage (modification de la voix )\nToux aboyante\nFièvre\nDysphagiée" },
  { id: 41, lang: "kh", page: "78", q: "41. INFECTION URINAIRE ET SYNDROME HEMOLYTIQUE ET UREMIQUE: Infection urinaire haute មានឈ្មោះថាតើទាក់ទងអ្វីជាមួយ malformations urinaires?", a: "R: + infection urinaire haute មានឈ្មោះ pyélonéphrite.\n+ ទាក់ទងជាមួយ malformation urinaires ធ្វើអោយមាន risque de septicémie ជាពិសេស nouveau-né et le nourrisson, ainsi qu'un risque ultérieur de séquelle parenchymateuse pouvant être responsable d'hypertension artérielle.\n+ Malformation urinaire ទាំងនោះមាន reflux vésico-urétéral, ou une lithiase." },
  { id: 42, lang: "fr", page: "78", q: "42. Les signes cliniques et paraclinique de la fièvre hémorragique de la dengue.", a: "+ signes cliniques :\nFebrile phase:\n• Clinical signs & symptoms are similar to DF.\n• Manifestations of bleeding is evidenced than DF:\nPositive tourniquet test\n- Petechiae\n- Ecchymosis, Epistaxis\nGum and Gl bleeding\n- Afebrile: Critical phase \"24h-48h\"\n• Fever starts to drop, usually on day 4 or 5 of disease, but:\nGeneral condition become deterioration\n- Somnolent\nAsthenia\n- Severe vomiting\n- Severe abdominal pain\n- No urine output 4 - 6h\n+ Signes paraclinique :\n- Thrombocytopenia (platelet <100 000/mm3)\n- Signs of plasma leakage:\n• Hemoconcentration → Hct↑(> 20% of Hct baseline).\n• Other plasma leakage signs:\n. Pleural effusion\nAscites\n. Hypoalbuminemia" },
  { id: 43, lang: "en", page: "78", q: "43. Definition of Idiopathic Thrombocytopenia Pupura?", a: "R: Immune thrombocytopenic purpura (IPT) is defined by an isolated thrombocytopenia which is secondary to increased destruction of platelets by the macrophages in the reticulo-endothelial system." },
  { id: 44, lang: "fr", page: "78", q: "44. Insufissance rénale aigue (5mn): Vous survellez un enfant de 5ans avec une dengue hémorragique avec choc...", a: "[Évaluer la perméabilité de la sonde vésicale, faire un remplissage si besoin ou une échographie rénale pour éliminer un obstacle fonctionnel/organique, et adapter les apports hydriques]" },
  { id: 45, lang: "fr", page: "78", q: "45. Clinical manifestations of lymphatic filariasis(15mn)", a: "+ Accidents précoces aigue\nAdénite aigue\nOrchiépididymite\nLymphangite rétrograde\n+ Accidents Tardifs Chronique\nPoumon éosinophile filarien\nChylurie\nAdénite chronique\nAdénolymphocèle\nElélphantiasis du membre inférieur ou supèrieur\nEléphantiasis du scrotum" },
  { id: 46, lang: "fr", page: "78", q: "46. Décrire les points essentiels à rechercher, lors de l'examen cutané et digestif du nouveau-né (5mn)", a: "Examen abdominal:\n- ombilic:\n+ la hernie ombilicale est banale et fréquente\n+ Infection au niveau du cordon: omphalite\nHerniés:\n+ hernie inguinale chez la fille\n+ hernie chez le garçon\n+ hernie ombilicale\n• Examen cutané:\n+ Un fin duvet recouvre souvent le nouveau-né pendant plusieurs jours: lanugo physiologique\n+ Des grains de millium (minuscules granulations blanches sur le nez, la face\n+ L'érythème toxique: tache bleutée (mongoloïde)\n+ Angiome plan: front, paupière supérieure, nez et nuque" },
  { id: 47, lang: "fr", page: "78", q: "47. Décrire les germes responsables de méningite purulente chez l'enfant et le nouveau-né. (10mn)", a: "Les germes responsables de méningite purulante chez l'enfant et le nouveau-né sont:\n- méningocoque, diplocoque Gram négatif: prédominant chez l'enfant>1an\n- Pneomocoque, cocci Gram positif: chez le nourrisson (60% des méningite purulantes chez enfant<1an)" },
  { id: 48, lang: "kh", page: "78", q: "48. មានផលប្រយោជន៍អ្វីដែលបែងចែក Infection Urinaire ជា infection Haute និង base?", a: "Infection haute: pyélonéphrite (upper UTI, pyelonephritis)\n→ Pathologie លើ parenchyme, bassinet\nInfection basses: cystite (lower UTI, cystitis)\n→ pathologie លើ Vessie" },
  { id: 49, lang: "fr", page: "78", q: "49. Quelle sont les signes Cliniques et paracliniques évocateurs d'une tuberculose chez l'enfant ?", a: "a. Signe cliniques Les signes cliniques non spécifiques: toux, - fièvre, - perte de poids, diminution de l'appétit, signes auscultatoires localisés.\nb. Singe paracliques\ni. Radiologie du thorachique\nii. IDR à la tuberculine\niii. L'endiscopie bronchique\niv. Les exams microbiologiques\nv. Le sérodiagnostic\nvi. L'amplification d'ADN par PCR" },
  { id: 50, lang: "fr", page: "78", q: "50. Signes clinique et paraclinique de la pleurésie purulente?", a: "Signes:\nFièvre\nToux sèche ou peu productive\nDyspnée (plus ou moins marquée selon l'abondance de l'épanchement)\nDouleur thoracique\nImmobilité d'un hémithorax\nMV↓ ou O\nMatité\nParaclinique\nRadiographie Pulmonaires\nEchographie\nBiologie" },
  { id: 51, lang: "kh", page: "78", q: "51. សរសេរមូលហេតុទាំង៥ ដែលធ្វើអោយមានលើសសម្ពាធឈាមឡើងខ្ពស់នៅក្នុងខួរក្បាល ?", a: "Masses expansives\nHydrocéphalies\nŒdème cérébral\nPhénomènes Vasomoteurs\nAVC ischémique" },
  { id: 52, lang: "kh", page: "78", q: "52. ចូរអ្នកសរសេរ Facteurs de risques របស់ Coqueluche.", a: "Enfant non vacciné.\nContact avec une personne infectée.\nÉpidémie.\nGrossesse." },
  { id: 53, lang: "kh", page: "78", q: "53. ចូររៀបរាប់អំពី Complication នៅក្នុងNéphrotique Syndrome?", a: "Hypovolémie\nThrombosis\nInfection (Spontaneous bacterial peritonitis)\nMalnutrition, anemia" },
  { id: 54, lang: "fr", page: "78", q: "54. Quels sont les signes de gravités à considérée pour une bronchiolite ?", a: "AEG\nApnée et Cyanose\nFR>60/min\nSaPO2<94% en air ambiant et au repos ou lors de la prise de biberon\nTroubles de la ventilation suspecté par clinique et confirmés par Rx\nTroubles digestifs (Vomissement, anorexie) compromettant l'hydratation, DSH avec perte de poids > 5%" },
  { id: 55, lang: "en", page: "78", q: "55. Clinical manifestation of measle", a: "Incubation: 8-12 days\nPhase prodromal\n Mild fever\n Conjunctivitis + photophobia\n Coryza cough\n Signe de Koplik" },
  { id: 56, lang: "fr", page: "78", q: "56. Différenciez l'ictére physiologique et pathologique ?", a: "Physiologique ou simple:\na. Nouveau-né à terme\nb. Isolé sans signe d'hémolyse\nc. Absent le 1° jour\nd. Peu intense (bilirubine totale <250 mmol/L)\ne. Touche surtout le garçon né par césarienne, allaité au sein et qui a perdu du poids prématuré\n- Immaturité hépatique\n- Photothérapie souvent necessaire\n\nIctére pathologique :\n+ ictères précoces:\n+ Infection maternity-fœtale\nIncompatibilité A, B, O et rhésus\n+ ictère prolongée\n+ ictère au lait de mère\n+ Maladie de Gilbert\n+ Hémolyses constitutionnelles" },
  { id: 57, lang: "fr", page: "78", q: "57. Décrire les moyens de diagnostique de méningite chez grands enfants.", a: "Syndrôme infectieux: Fiévre à début souvent brutal.\nSyndrôme méningé: Céphalée, vomissement\nExamen:\n Raideur de la nuque\n Signe de kernig\n Signe de Brudzinski" },
  { id: 58, lang: "kh", page: "78", q: "58. និយមន័យ fièvre prolongé de l'enfant", a: "ក ចំពោះទារក (Nourrisson): La définition du fièvre prolongé du nourrisson est définie par une température centrale supérieure à 38 degré C et elle dépasse 5 jours sans interruption.\nខ ចំពោះក្មេងធំ: La fièvre prolongé de l'enfants est définie par une température centrale supérieure à 38 degré C et elle dépasse 10-15 jours." },
  { id: 59, lang: "kh", page: "78", q: "59. តើសណ្ឋានclinique ទាំង ២formes របស់Syndrome Hémolytique et Urémique មានយ៉ាងដូចម្តេច?", a: "Form Typique (nourrisson):\n. Prodrome: Fièvre, Pharyngite, Diarrhée, Méléna\nDébut brutal de SHU: anémie sévère, Thrombopénie, Insuffisance Rénal\n. Autre viscères atteinte: atteinte colique, atteinte hépatique, atteinte pancréatique, atteinte au système nerveux central.\n\nForm Atypique :\n. L'absence de diarrhée prodromique.\n. L'absence de prédominance saisonière\n. La survenue à n'importe quel âge\n. Début parfois progressive et poussée succesive pendant plusieur mois\n. Peut recutes pendant plusieur année\n. Le caractère parfois familiale" },
  { id: 60, lang: "fr", page: "78", q: "60. Données les signes Clinique de laryngite sus glottique.", a: "La Fièvre (39-40degré C), La Dyspnée layngé, La dysphagie, Des difficulté pour avaler, toux aboyante et modification de la voix" },
  { id: 61, lang: "fr", page: "78", q: "61. Le prise en charge de prématuré", a: "- Anté-natale\no Dépistage et prévention primaire\no Prévention secondaire: prévention chez les femmes à risque\no Prévention tertiaire: prévention des complications\nAccouchement à proximité d'une réanimation néonatale\nCorticothérapie anténatale\n- À la naissance\no Réchauffer\no Mesures d'asepsie stricte\no Réanimation néonatale si nécessaire\no Monitoring cardiorespiratoire\no Vitamine K (2 mg IVD) et collyre antibiotique\no Alimentation précoce\no Surveillance\n- Post-natale (prise en charge des complications)\no Maladie des membranes hyalines\no HTAP: monoxyde d'azote (NO)\no Persistance du canal artériel: cure d'ibuprofène et ligature chirurgicale si échec\no Apnées d'origine centrale: caféine, doxapram\no Entérocolite ulcéronécrosante\no Ictère\no Hyperglycémie\no Fuite sodée urinaire\no Anémie\no Infection" },
  { id: 62, lang: "fr", page: "78", q: "62. Décrire les germes responsables de méningite purulente chez l'enfant et leur caractéristiques.", a: ". Méningocoque\n. Pneumocoque\n. Haemophilus\n+ Autres bactéries:\n. Salmonella\n. Staphylocoque ou bacille gram négatif\n. Germes opportuniste\n. BK" },
  { id: 63, lang: "fr", page: "78", q: "63. Les éléments de gravité du paludisme.", a: ". Coma, Convulsion\n. Ictère\n. Hypoglycémie\n. Insuffisance rénale\n. Toux parasitaire\n. Oedème aiguë du poumon\n. Anémie\n. Hémoglobinurie\n. Thrombopénie" },
  { id: 64, lang: "kh", page: "78", q: "64. បើមិនមានវិធានការ ការពារនោះទេតើការឆ្លងមេរោគអេដស៍ទៅកូនរបស់គាត់កើតមាននៅក្នុងដំណាក់កាលណាខ្លះ?", a: ". Before birth\n. During delivery\n. After delivery" },
  { id: 65, lang: "fr", page: "78", q: "65. Le diagnostic du syndrome néphrotique.", a: ". Protéinurie >3g/24h\n. Hypoalbuminémie <30g/L\n. Oedème\n. Hyperlipidémie" },
  { id: 66, lang: "fr", page: "78", q: "66. Classification la broncho pneumonie.", a: ". Stade I léger: VEMS supérieur où égale à 80%\n. Stade II modéré: VEMS comprise entre 50 et 80%\n. Stade III sévère: VEMS comprise entre 30 et 50%" },
  { id: 67, lang: "en", page: "78", q: "67. Guillain-Barré syndrome: Describe about Sign and symptom, Treatment, Diagnosis and criteria.", a: "+ signs and symptoms :\nmuscle paralysis symmetrical rapidly progress in ascending fashion over period of hours to day.\n- affect nerves cranials (drooling, difficulty swallowing)\n- 30% affect autonomic nerve\n- loss of pain, temperature, bladder dysfunction orthopedic hypotension\n+ Diagnosis:\n- cerebrospinal fluid analysis and test of nerves and muscles\nElectromyography and nerve conduction studie\n+ Criteria: progressive weakness leg and arm areflexia\n+ Treatment:\n- supportive care\n- intubation (when have difficult of breathness)\n- plasmapheresis\n- IV Ig first (easy and safe)\n- physiothearapy" },
  { id: 68, lang: "fr", page: "78", q: "68. Diagnostic du paludisme", a: "+ physical examination: Fever, pallor, jaundice, splenomegaly\n+ Microscopy: Blood smear on the microscope slide\n+ Thick blood film: Use for detecting malaria: detection of even levels low of parasitaemia, determining parasite density and monitoring treatment response.\n+ Antigen Detection Methods are Rapid and Precise." },
  { id: 69, lang: "fr", page: "78", q: "69. Tuberculose chez l'enfant: Quelle sont les signes clinique évocateur d'une tuberculose chez l'enfant ? Et quelle sont les examens para clinique doit être fait pour infirmier diagnostique ?", a: "+ Signes cliniques Les signes cliniques non spécifiques: toux, fièvre, - perte de poids, diminution de l'appétit, signes auscultatoires localisés.\n+ Signes paracliques:\ni. Radiologie du thorachique\nii. IDR à la tuberculine\niii. L'endoscopie bronchique\niv. Les exams microbiologiques\nv. Le sérodiagnostic\nvi. L'amplification d'ADN par PCR" },
  { id: 70, lang: "fr", page: "78", q: "70. Cause of syndrome d'hypertension intracrânienne (SHIC) ?", a: "+ Les signes cliniques :\nVomissement en jet, Trouble de visuel, Vertige, Cephalee intense, Crises comitiales\n+ Cause of SHIC:\n- Masses expansives\n- Hydrocéphalies\n- Œdème cérébral\n- Phénomènes Vasomoteurs\n- AVC ischémique" },
  { id: 71, lang: "en", page: "78", q: "71. Children with HIV/AIDS: How to diagnosis HIV in infant under 18 months in case the HIV DNA PCR test is not available ?", a: "If HIV PCR testing is not immediately available for HIV-exposed infants under 18 months, a presumptive diagnosis of severe HIV disease may be made in certain cases:\n+ The infant is confirmed to be HIV exposed by antibody testing\n+ Diagnosis of any AIDS-indicator condition(s) has been made;\n+ The infant is symptomatic with 2 or more of the following:\n- Oral Thrush\n- Severe pneumonia\n- Severe sepsis" },
  { id: 72, lang: "kh", page: "78", q: "72. Pneumonie: ចូរធ្វើការប្រៀបធៀបរវាង pneumonie franche lobaire gauche នឹង pneumonie viral?", a: "+ Pneumonia flanche lobaire aigue:\nbrutal-fièvre, Douleur thoracique, Douleur abdominal - Frissons, Crépitants localisée, Rx: alvéolaire systématisé, unilatéral - CRP> 80mg/L - PNN> 12g/L\n\n+ Pneumonia Virale:\nDébut progressif, Wheezing/asthme, Auscultation bilatéral, Fièvre au second plan, Signes extra-pulmonaires, Rx: broncho-interstitiel bilatéral - Distension - Biologie non spécifique" },
  { id: 73, lang: "fr", page: "78", q: "73. Anémie du nourrisson: Les anémies hémolytiques constitutionnelles d'origine héréditaire ?", a: "Les anémies hémolytiques héréditaires sont toutes liées à un défaut constitutionnel des hématies affectant leur membrane, leur contenu enzymatique, ou la structure de l'hémoglobine (normochrome régéneratiove, réticulocytes >12000).\nTest de COOMBS:\n- Positive (+): Anémie hémolytiques autoimmune\n- Negative (-): Anémie héréditaire (Drépanocytose, Thalassemia, Déficit G6PD, Pyruvate-kinase)" },
  { id: 74, lang: "fr", page: "78", q: "74. Diagnostic du tétanos :", a: "Signe clinique: statue vaccinal défectueux, trismus sans fièvre, faciès caractéristique\nAucun test biologique pour diagnostic\nIsolement de Clostridium tetani au niveau de la plaie non utile" },
  { id: 75, lang: "fr", page: "78", q: "75. Traitement/Prise en charge de la coqueluche chez le nourrisson :", a: "+ Hospitalisation pour les nourrissons de moins de 3 mois\n+ Surveillance des enfants atteints.\n+ Isolement et éviction scolaire de 30 jours à partir du début des quintes\n+ Oxygène et correction des troubles hydro-électrolytique si besoin.\n+ Dépister les apnées pour des nourrissons.\n+ Erythromycine pendant la période de début: 50 mg/kg/j en 4 prises.\n+ Surveillance du nourrisson dans les formes graves\n+ Isoler les personnes infectées.\n+ Vaccination." },
  { id: 76, lang: "en", page: "78", q: "76. Management for children age 3M to 36M has febrile :", a: "- It base on: anamnestic information and clinical examination.\n- Anamnestic information specify on:\n. characteristic of fever (date of onset)\n. history and type of thermal curve\n. initial and current accompany signs\n. dangerous signs of general condition\n. drugs intake\n. medical and surgical history\n. traveling history\n. food ingestion\n- Clinical examination:\n. should be completed and symmetric\n. + paraclinic (CBC, specific serology, X-ray,...)" },
  { id: 77, lang: "kh", page: "78", q: "77. និយមន័យនៃសភាពលឿង (Ictère) :", a: "ជាការលេចឡើងនៃសភាពលឿងនៅលើស្បែក ឬកន្លែងផ្សេងៗទៀតដូចជាក្នុងភ្នែក ទឹកនោមជាដើម।" },
  { id: 78, lang: "fr", page: "78", q: "78. Signes Cliniques de rhino-pharyngite de l'enfant au dessus de 2 ans:", a: "- La fièvre: brûtal, éleve, a 39c -40c\n- La muqueuse nasale est rouge\n- L'enfant respire bouche ouverte\n- La céphalée est inconstante\n- La toux et larmoiment existent plus ou moons.\n- La dyphagie (cavité bucco-pharyngé mais les amydales sont aspect subnormal, non infectées)" },
  { id: 79, lang: "fr", page: "78", q: "79. Pourquoi l'infection urinaire peut-elle être grave chez le nouveau-né ?", a: "Elle peut engendrer facilement un risque de septicémie particulièrement chez le nouveau-né et le nourrisson, ainsi qu'un risque ultérieur de séquelle parenchymateuse pouvant être responsable d'hypertension artérielle. L'infection urinaire peut révéler une malformation des voies urinaires (reflux vésico-urétéral, lithiase)." },
  { id: 80, lang: "fr", page: "78", q: "80. Diagnostic de la méningite chez le grand enfant :", a: "- syndrome infectieux (fièvre à début souvent brutal, rhinopharyngite ou otite)\n- syndrome méningé: céphalées, vomissement, refus alimentaire, photophobia\n- raideur de la nuque\n- signe de Kernig\n- signe de Brudzinski\n- Examen du LCR" },
  { id: 81, lang: "en", page: "78", q: "81. Schistosomiasis Treatment and Control:", a: "> Treatment:\n- Praziquantel (40mg/kg/day, PO 2 times a day) for Schistosomiasis haematobium.\n- Mansoni, and Intercalatum: 160mg/kg/day, PO 3 times a day for schistosomiasis japonica and mekongi.\n- S. Mansoni: oxamniquine effective in some areas.\n> Control:\n• Improved sanitation\n• Focal application of molluscicidals\n• Animal vaccination" },
  { id: 82, lang: "fr", page: "78", q: "82. Signes Cliniques de la Bronchiolite (Phase débutant, Phase d'état, Signes de gravité) :", a: "• Incubation de 3-8 jours\n• Phase Débutant = Phase ORL: Allure banale avec fièvre élevée voir modérée, signes rhino-pharyngés, toux sèche.\n• Phase d'état = Phase Pulmonaire: Vomissements, fatigue lors du biberon => refuse de tétée, apnées chez le nourrisson <3M. Toux fréquente par quintes, dyspnée et sifflement expiratoire. Signes de lutte (score de Silverman).\n• Signes de gravité: FR >60/mn, cyanose, sueurs, troubles de la conscience.\n• Auscultation: Râles bronchiques sibilants, râles sous crépitants disséminés, distension thoracique." },
  { id: 83, lang: "fr", page: "78", q: "83. Caractères de l'ictère néonatal pathologique :", a: "- début précoce avant 24 heures de vie (le plus souvent);\n- en cas d'hémolyse sévère: syndrome anémique, hépatosplénomégalie\n- ictère à bilirubine libre d'intensité plus forte;\n- anémie (normo-)macrocytaire, hyper-réticulocytose." },
  { id: 84, lang: "en", page: "78", q: "84. Clinical manifestation of trichinosis:", a: "Diarrhea, Abdominal pain, Fatigue, Nausea and vomiting" },
  { id: 85, lang: "en", page: "78", q: "85. Specific Treatment of Nephrotic syndrome:", a: "+ Treatment of initial episode of NS: Prednisolone 60 mg/m2/day (or 2 mg/kg/day) not exceeded 80mg/24h, Duration: 4 week\n+ Treatment of relapse > 3 months after treatment completion: (60 mg/m2/d until 7 days after proteinuria negative)\n+ Treatment of relapse ≤ 3 months after treatment completion." },
  { id: 86, lang: "en", page: "78", q: "86. Isolated thrombocytopenia (<100.000/mm3) diagnosis features in ITP:", a: "- Isolated thrombocytopenia (<100.000/mm3) and anemia if history of significant bleeding.\n- Giant platelet on the blood smear (Increase MPV).\n- Bone marrow aspiration show normal or increased megakaryocytes, normal myeloid/erythroid elements, absence of abnormal cell population." },
  { id: 87, lang: "en", page: "78", q: "87. Why examine a newborn baby? What to examine?", a: "Because of:\n• Detection of abnormalities and to allow referral to appropriate service in a timely fashion\n• Parent information and relationship building\n• Provide the family with an opportunity to ask questions about their baby\nWhat to examine? Vital signs, Physical exam, General exam, Neurological exam, Estimation of gestational age." },
  { id: 88, lang: "en", page: "78", q: "88. IV fluid therapy protocol for DHF grade I & II", a: "Start IV fluid 1.5-3ml/kg/h crystalloid solutions over 1-3h\n• If Improvement: IV to 3 ml/kg/h for another 3h -> Reevaluation VS hourly -> lower rate to 1.5 ml/kg/h for another 3h -> lower rate to 1.5 ml/kg/h over 48h, then stop.\n• If No improvement: Continue same rate for another 1-3h -> Reevaluate VS hourly and recheck Hct.\n- If Improvement: follow improvement steps.\n- If Deterioration: IV to 3-6 ml/kg/h for 1-3h.\n- If More aggravation: See DHF grade III or IV." },
  { id: 89, lang: "fr", page: "78", q: "89. Signes de gravité de la méningite bactérienne :", a: "- Hémodynamique: augmentation fréquence cardiaque, diminution temps de recoloration, extrémités froides, absence de diurèse, diminution pression artérielle ou collapsus.\n- Cutanés: purpura rapidement extensif ou nécrotique\n- Neurologique: trouble de la conscience, parfois coma" },
  { id: 90, lang: "fr", page: "78", q: "90. Éléments de mauvais pronostic de la méningite :", a: "- Retard à la mise en route d'un traitement bactéricide\n- Jeune âge (nourrisson)\n- Germe (pneumocoque)\n- Gravité du tableau neurologique initial (formes comateuses)\n- Existence d'un collapsus associé ou de signes d'hypertension intracrânienne." },
  { id: 91, lang: "fr", page: "78", q: "91. Définition de la méningite :", a: "La méningite est une inflammation des méninges dont l'étiologie infectieuse virale est la plus fréquente." },
  { id: 92, lang: "fr", page: "78", q: "92. Physiopathologie des méningites chez l'enfant :", a: "- Germes responsables chez l'enfant (nourrisson et grand enfant): germes de portage du rhino-pharynx.\n- Pénétration des germes dans le LCR se fait par voie hématogène (septicémie) ou contamination directe.\n- Germes se multiplient très rapidement dans le LCR.\n- Réponse de l'hôte: production de cytokines (TNF alpha, interleukine 1 et 6)." },
  { id: 93, lang: "fr", page: "78", q: "93. Causes des méningites virales :", a: "- Enterovirus\n- Paramyxovirus\n- Virus echo\n- Adenovirus\n- Herpes virus" },
  { id: 94, lang: "fr", page: "78", q: "94. Comment faire le diagnostic de méningite chez le nourrisson ?", a: "Diagnostic plus difficile:\n- Enfant grognon, Somnolence, Refus répété du biberon, Convulsions fébriles.\n- Examen: Tension de la fontanelle en position assise, hypotonie de la nuque ou raideur, signes neurologiques de localisation, coexistence de signes d'infections associées." },
  { id: 95, lang: "fr", page: "78", q: "95. Examens de confirmation de méningite (LCR) :", a: "Examen du LCR: LCR hypertendu, perte de limpidité.\n- Nombre de cellules: anormal si > 10/mm3\n- Protéinorachie: anormal si > 0,45 g/l\n- Rapport glucose LCR / sang < 0,40" },
  { id: 96, lang: "en", page: "78", q: "96. What is the diagnosis of asthma ?", a: "- History and patterns of symptoms\n- Measurements of lung function: Spirometry, Peak expiratory flow\n- Measurement of airway responsiveness\n- Measurements of allergic status\n- Reversibility of lung function abnormalities" },
  { id: 97, lang: "kh", page: "78", q: "97. Common risk factors in asthma (រៀបរាប់ពី common risk factors ក្នុងជម្ងឺហឺត) :", a: "- Allergen: domestic dust mites, animal with fur, cockroach, pollens and molds\n- Respiratory (viral) infections\n- Strong emotional expressions\n- Exercise\n- Chemical irritants and drugs (aspirin and beta blocker)\n- Tobacco smoke / Air pollution / Occupational irritants\n- Changes in temperature" },
  { id: 98, lang: "en", page: "78", q: "98. Management of asthma (Six parts) :", a: "- Assess and monitor asthma severity\n- Educate patients to develop a partnership in asthma care\n- Avoid exposure to risk factors\n- Establish individual medication plans for long term management\n- Establish individual plans to manage asthma attacks\n- Provide regular follow-up care." },
  { id: 99, lang: "kh", page: "78", q: "99. ឱសថសំរាប់ព្យាបាលហឺតមាន ២ ប្រភេទ :", a: "- Controller medications\n- Reliever medications" },
  { id: 100, lang: "kh", page: "78", q: "100. ហេតុអ្វីបានជាគេប្រើ Inhaled medication ក្នុងការព្យាបាលហឺតជាជម្រើសល្អជាងគេ?", a: "Because of their high therapeutic ratio:\n• High concentrations of drugs are delivered directly to the airways\n• With potent therapeutic effects\n• And few systemic side effects." },
  { id: 101, lang: "en", page: "78", q: "101. Goal management of asthma :", a: "- Achieve and maintain control of symptoms\n- Maintain normal activity levels, including exercise\n- Maintain pulmonary function as close to normal as possible\n- Prevent asthma exacerbations\n- Avoid adverse effects from asthma medications\n- Prevent asthma mortality" },
  { id: 102, lang: "fr", page: "78", q: "102. Complications de la rougeole :", a: "- Complications respiratoires: pneumonie, surinfections bactériennes, pharyngite\n- Complications neurologiques: encéphalite\n- Complications digestives: diarrhée\n- Complications cardiaques: myocardite\n- Complications oculaires: conjonctivite, kératite\n- Complications ORL\n- Complications hématologiques: purpura thrombopénique, hémorragie" },
  { id: 103, lang: "fr", page: "78", q: "103. Définition de l'ictère néonatal :", a: "C'est la jaunisse due à l'hyperbilirubinémie du nouveau-né." }
];

// ==========================================
// 2. STATE MANAGEMENT & CONTROLLERS
// ==========================================
let currentFilter = 'all'; // 'all', 'kh', 'fr', 'en'
let filteredQuestions = [...questions];
let currentIndex = 0;

// DOM Elements Reference
const questionTitleEl = document.getElementById('question-title');
const questionTextEl = document.getElementById('question-text');
const answerTextEl = document.getElementById('answer-text');
const pageNumEl = document.getElementById('page-num');
const btnPrev = document.getElementById('btn-prev');
const btnNext = document.getElementById('btn-next');

// Initial Load
document.addEventListener('DOMContentLoaded', () => {
    updateUI();
});

// Function to render Current Question
function updateUI() {
    if (filteredQuestions.length === 0) {
        if(questionTitleEl) questionTitleEl.innerText = "គ្មានទិន្នន័យ";
        if(questionTextEl) questionTextEl.innerText = "មិនមានសំណួរសម្រាប់ភាសានេះទេ";
        if(answerTextEl) answerTextEl.innerText = "";
        if(pageNumEl) pageNumEl.innerText = "ទំព័រ -";
        return;
    }

    const item = filteredQuestions[currentIndex];
    
    // Update HTML Content
    if(questionTitleEl) questionTitleEl.innerText = `សំណួរទី ${currentIndex + 1} / ${filteredQuestions.length}`;
    if(questionTextEl) questionTextEl.innerText = item.q;
    if(answerTextEl) answerTextEl.innerText = item.a;
    if(pageNumEl) pageNumEl.innerText = `ទំព័រ ${item.page}`;

    // Enable/Disable Pagination Buttons
    if(btnPrev) btnPrev.disabled = currentIndex === 0;
    if(btnNext) btnNext.disabled = currentIndex === filteredQuestions.length - 1;
}

// ==========================================
// 3. EVENT HANDLERS (NEXT, PREV, FILTER)
// ==========================================
function nextQuestion() {
    if (currentIndex < filteredQuestions.length - 1) {
        currentIndex++;
        updateUI();
    }
}

function prevQuestion() {
    if (currentIndex > 0) {
        currentIndex--;
        updateUI();
    }
}

function filterLanguage(lang) {
    currentFilter = lang;
    if (lang === 'all') {
        filteredQuestions = [...questions];
    } else {
        filteredQuestions = questions.filter(q => q.lang === lang);
    }
    currentIndex = 0; // Reset back to first question of the filter
    updateUI();
}
